---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master
      - main
      - feat-rpm

jobs:
  #lint:
  #  name: lint
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Check-out code
  #      uses: actions/checkout@v2

  #    - name: Set-up Python 3
  #      uses: actions/setup-python@v2
  #      with:
  #        python-version: '3.x'

  #    - name: Install dependencies
  #      run: |
  #        pip3 install salt-lint
  #        sudo apt install rubocop

  #    - name: Lint code
  #      run: |
  #        salt-lint demo
  #        rubocop test/*.rb

  #kitchen:
  #  name: test-kitchen
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Check-out code
  #      uses: actions/checkout@v2

  #    - name: Set-up Python 3
  #      uses: actions/setup-python@v2
  #      with:
  #        python-version: '3.x'

  #    - name: Install dependencies
  #      run: |
  #        sudo apt install test-kitchen ruby-kitchen-salt ruby-kitchen-docker openssh-client
  #        sudo gem install inspec kitchen-inspec

  #    - name: Run test-kitchen tests
  #      run: |
  #        kitchen test

  rpm:
    name: create-rpm
    runs-on: ubuntu-latest
    steps:
      - name: Check-out code
        uses: actions/checkout@v2

      - name: build RPM package
        id: rpm
        uses: naveenrajm7/rpmbuild@master
        with:
          spec_file: "demo-formula.spec"

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Binary RPM
          path: ${{ steps.rpm.outputs.rpm_dir_path }}
